# Generated by Django 2.2.4 on 2019-10-14 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('builds', '0001_initial'),
        ('assemblies', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysnapshot',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_snapshots', to='inventory.Inventory'),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='location',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_snapshots', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='builds.InventorySnapshot'),
        ),
        migrations.AddField(
            model_name='buildsnapshot',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='build_snapshots', to='builds.Build'),
        ),
        migrations.AddField(
            model_name='buildsnapshot',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_snapshots', to='inventory.Deployment'),
        ),
        migrations.AddField(
            model_name='buildsnapshot',
            name='location',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_snapshots', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='buildaction',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='builds.Build'),
        ),
        migrations.AddField(
            model_name='buildaction',
            name='location',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='buildaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='build',
            name='assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='assemblies.Assembly'),
        ),
        migrations.AddField(
            model_name='build',
            name='location',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='locations.Location'),
        ),
    ]
