# Generated by Django 2.2.1 on 2019-06-26 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_location_root_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('buildadd', 'Add Build'), ('locationchange', 'Location Change'), ('subassemblychange', 'Subassembly Change'), ('assigntodeployment', 'Assign to Deployment'), ('removefromdeployment', 'Remove from Deployment'), ('deploymentburnin', 'Deployment Burnin'), ('deploymenttosea', 'Deployment to Sea'), ('deploymentrecover', 'Deployment Recovered'), ('test', 'Test'), ('note', 'Note'), ('historynote', 'Historical Note'), ('ticket', 'Work Ticket'), ('flag', 'Flag'), ('movetotrash', 'Move to Trash')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('detail', models.TextField(blank=True)),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='builds.Build')),
                ('location', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='locations.Location')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'action_type'],
            },
        ),
    ]
