# Generated by Django 2.2.1 on 2019-06-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_buildaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='build_notes',
            field=models.TextField(blank=True),
        ),
    ]
