# Generated by Django 2.2.4 on 2019-12-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_auto_20191022_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='build_number',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
