# Generated by Django 2.2.1 on 2019-06-26 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_build_build_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='build',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
