# Generated by Django 2.2.1 on 2019-06-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_auto_20190626_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='is_deployed',
            field=models.BooleanField(default=False),
        ),
    ]
