# Generated by Django 2.2.9 on 2020-01-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0005_auto_20191217_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='build_number',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
