# Generated by Django 2.2.1 on 2019-07-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0005_build_is_deployed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildaction',
            name='action_type',
            field=models.CharField(choices=[('buildadd', 'Add Build'), ('locationchange', 'Location Change'), ('subassemblychange', 'Subassembly Change'), ('startdeploy', 'Start Deployment'), ('removefromdeployment', 'Remove from Deployment'), ('deploymentburnin', 'Deployment Burnin'), ('deploymenttosea', 'Deployment to Sea'), ('deploymentrecover', 'Deployment Recovered'), ('test', 'Test'), ('note', 'Note'), ('historynote', 'Historical Note'), ('ticket', 'Work Ticket'), ('flag', 'Flag'), ('movetotrash', 'Move to Trash')], max_length=20),
        ),
    ]
