# Generated by Django 2.2.1 on 2019-07-15 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0006_auto_20190701_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='time_at_sea',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
