# Generated by Django 2.2.1 on 2019-07-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0007_build_time_at_sea'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='flag',
            field=models.BooleanField(choices=[(True, 'Flagged'), (False, 'Unflagged')], default=False),
        ),
    ]
