# Generated by Django 2.2.9 on 2020-02-27 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0008_auto_20200226_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='assembly',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='assemblies.Assembly'),
            preserve_default=False,
        ),
    ]
