# Generated by Django 2.2.1 on 2019-07-17 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0009_buildsnapshot_inventorysnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildsnapshot',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='build_snapshots', to='builds.Build'),
        ),
    ]
