# Generated by Django 2.2.9 on 2020-03-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0010_auto_20200309_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'ordering': ['assembly_revision', 'build_number']},
        ),
    ]
