# Generated by Django 2.2.1 on 2019-07-17 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0011_buildsnapshot_deployment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildsnapshot',
            name='time_at_sea',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
