# Generated by Django 2.2.10 on 2020-04-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0011_auto_20200309_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildaction',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at', 'action_type']},
        ),
    ]
