# Generated by Django 2.2.13 on 2020-06-11 17:42

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0016_auto_20200531_1905'),
    ]

    operations = []
