# Generated by Django 2.2.13 on 2020-06-17 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0017_auto_20200611_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photonote',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='build_photos', to='inventory.Action'),
        ),
    ]
