# Generated by Django 3.0.10 on 2020-10-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0019_auto_20200923_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
