# Generated by Django 3.1.3 on 2021-01-13 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0020_auto_20201014_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildHyperlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=1000)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperlinks', to='builds.build')),
            ],
            options={
                'ordering': ['text'],
            },
        ),
    ]
