# Generated by Django 2.0 on 2017-12-08 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('doc_type', models.CharField(choices=[('Test', 'Test'), ('Design', 'Design')], max_length=20)),
                ('doc_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('revision', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('documentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='parts.Documentation')),
            ],
        ),
    ]
