# Generated by Django 2.2.4 on 2019-10-14 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdefinedfields', '0001_initial'),
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='user_defined_fields',
            field=models.ManyToManyField(blank=True, related_name='parts', to='userdefinedfields.Field'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='parts.Part'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='parts.Revision'),
        ),
    ]
