# Generated by Django 2.0 on 2017-12-08 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20171208_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='documentation',
        ),
        migrations.AddField(
            model_name='documentation',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='parts.Part'),
        ),
        migrations.AddField(
            model_name='part',
            name='parent_assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='parts.Part'),
        ),
    ]
