# Generated by Django 2.0 on 2017-12-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_auto_20171208_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='assembly',
            field=models.CharField(blank=True, choices=[('Halo', 'Halo'), ('Cables', 'Cables'), ('Instrument Well', 'Instrument Well'), ('Sensors', 'Sensors')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='node',
            field=models.CharField(blank=True, choices=[('Buoy', 'Buoy'), ('NSIF', 'NSIF'), ('MFN', 'MFN')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='doc_type',
            field=models.CharField(choices=[('Test', 'Test Documentation'), ('Design', 'Design Documentation')], max_length=20),
        ),
    ]
