# Generated by Django 2.2.4 on 2019-10-23 17:35
"""
Auto-generate default Part Types for start up
"""
from django.db import migrations
from django.apps import apps

PartType = apps.get_model('parts', 'PartType')

def create_part_types(apps, schema_editor):
    part_types = ['Cable', 'Electrical', 'Instrument', 'Mechanical']

    for part_type in part_types:
        obj, created = PartType.objects.get_or_create(name=part_type)


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_auto_20191023_1408'),
    ]

    operations = [
        migrations.RunPython(create_part_types),
    ]
