# Generated by Django 2.2.9 on 2020-04-03 16:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20191023_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='max_cal_sigdig',
            field=models.DecimalField(blank=True, decimal_places=0, default='0.00', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
