# Generated by Django 2.2.10 on 2020-06-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20191023_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
