# Generated by Django 2.0 on 2017-12-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20171208_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='parent_assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_parts', to='parts.Part'),
        ),
    ]
