# Generated by Django 2.2.9 on 2020-04-06 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_part_max_cal_sigdig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='max_cal_sigdig',
        ),
        migrations.AddField(
            model_name='part',
            name='cal_dec_places',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
