# Generated by Django 2.2.9 on 2020-04-20 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_auto_20200406_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='cal_dec_places',
            field=models.IntegerField(blank=True, default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
