# Generated by Django 2.0 on 2017-12-13 15:40

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_auto_20171213_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='parent_assembly',
        ),
        migrations.AddField(
            model_name='part',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='parts.Part'),
        ),
    ]
