# Generated by Django 2.0 on 2017-12-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_auto_20171213_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='assembly',
        ),
        migrations.RemoveField(
            model_name='part',
            name='node',
        ),
    ]
