# Generated by Django 2.2.13 on 2020-06-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_auto_20200420_1935'),
        ('parts', '0005_auto_20200604_2019'),
    ]

    operations = [
    ]
