# Generated by Django 2.2.13 on 2020-09-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_merge_20200617_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttype',
            name='ccc_toggle',
            field=models.BooleanField(default=False),
        ),
    ]
