# Generated by Django 2.2.13 on 2020-10-14 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_merge_20200617_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='cal_dec_places',
            field=models.IntegerField(blank=True, default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32)]),
        ),
    ]
