# Generated by Django 2.2.13 on 2020-10-15 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_auto_20201014_2007'),
        ('parts', '0009_parttype_ccc_toggle'),
    ]

    operations = [
    ]
