# Generated by Django 3.0.10 on 2020-10-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_parttype_ccc_toggle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttype',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
