# Generated by Django 3.0.10 on 2020-10-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_auto_20201014_1253'),
        ('parts', '0010_merge_20201015_2202'),
    ]

    operations = [
    ]
