# Generated by Django 2.2.13 on 2020-11-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_merge_20201015_1353'),
        ('parts', '0010_merge_20201015_2202'),
    ]

    operations = [
    ]
