# Generated by Django 2.0 on 2018-01-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_auto_20171222_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentation',
            options={'ordering': ['doc_type', 'name']},
        ),
        migrations.AlterField(
            model_name='documentation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
