# Generated by Django 3.0.10 on 2020-11-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0011_merge_20201016_1334'),
        ('parts', '0011_merge_20201105_1645'),
    ]

    operations = [
    ]
