# Generated by Django 2.0 on 2018-01-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0011_auto_20180103_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='parent',
            new_name='parent_assembly',
        ),
    ]
