# Generated by Django 3.0.10 on 2020-10-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0011_merge_20201016_1334'),
        ('parts', '0011_merge_20201015_1401'),
    ]

    operations = [
    ]
