# Generated by Django 2.0 on 2018-01-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0012_auto_20180103_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='parent_assembly',
            new_name='parent',
        ),
    ]
