# Generated by Django 3.0.10 on 2020-11-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0012_merge_20201106_1538'),
        ('parts', '0012_merge_20201016_1512'),
    ]

    operations = [
    ]
