# Generated by Django 3.0.10 on 2020-11-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0013_merge_20201110_1515'),
        ('parts', '0013_merge_20201106_1900'),
    ]

    operations = [
    ]
