# Generated by Django 2.0 on 2018-01-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0013_auto_20180103_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='revision',
            field=models.CharField(blank=True, default=None, max_length=100),
            preserve_default=False,
        ),
    ]
