# Generated by Django 3.0.10 on 2020-11-16 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0014_merge_20201116_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='cal_dec_places',
            field=models.IntegerField(blank=True, default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32)]),
        ),
    ]
