# Generated by Django 2.0 on 2018-01-24 20:30

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0014_auto_20180122_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='location',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='parts', to='locations.Location'),
        ),
    ]
