# Generated by Django 3.1.3 on 2021-02-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0015_auto_20201116_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
