# Generated by Django 2.0 on 2018-02-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0015_auto_20180124_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='doc_link',
            field=models.CharField(max_length=1000),
        ),
    ]
