# Generated by Django 3.1.3 on 2021-02-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0016_auto_20210204_2245'),
        ('parts', '0016_auto_20210106_1824'),
    ]

    operations = [
    ]
