# Generated by Django 3.1.3 on 2021-06-24 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0017_merge_20210209_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='cal_dec_places',
            field=models.IntegerField(blank=True, default=32, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32)]),
        ),
    ]
