# Generated by Django 2.0 on 2018-02-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0017_auto_20180228_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='friendly_name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
