# Generated by Django 2.0 on 2018-03-13 15:14

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0018_auto_20180228_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='location',
            field=mptt.fields.TreeManyToManyField(related_name='parts', to='locations.Location'),
        ),
    ]
