# Generated by Django 3.1.3 on 2021-08-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0018_auto_20210624_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='revision',
        ),
    ]
