# Generated by Django 3.1.3 on 2021-09-28 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0021_auto_20210928_1900'),
        ('parts', '0019_remove_part_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='bulk_upload_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='ooi_ci_tools.bulkuploadevent'),
        ),
    ]
