# Generated by Django 2.0 on 2018-03-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0019_auto_20180313_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='parent',
        ),
        migrations.AddField(
            model_name='part',
            name='parent',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='_part_parent_+', to='parts.Part'),
        ),
    ]
