# Generated by Django 2.0 on 2018-03-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0020_auto_20180322_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='parent',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='_part_parent_+', to='parts.Part'),
        ),
    ]
