# Generated by Django 2.0 on 2018-03-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0021_auto_20180322_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['name']},
        ),
        
    ]
