# Generated by Django 2.0 on 2018-03-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0022_auto_20180322_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='level',
        ),
        migrations.RemoveField(
            model_name='part',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='part',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='part',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='part',
            name='parent',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='children', to='parts.Part'),
        ),
    ]
