# Generated by Django 2.0 on 2018-03-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0023_auto_20180322_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='parent',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='children', to='parts.Part'),
        ),
    ]
