# Generated by Django 2.0 on 2018-04-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0025_part_part_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=models.CharField(blank=True, choices=[('Cable', 'Cable'), ('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Sensor', 'Sensor')], max_length=50),
        ),
    ]
