# Generated by Django 2.0 on 2018-04-16 17:30

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0027_auto_20180416_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='parts.PartType'),
        ),
    ]
