# Generated by Django 2.0 on 2018-04-16 18:24

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0029_auto_20180416_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='parts.PartType'),
        ),
    ]
