# Generated by Django 2.0 on 2018-04-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0030_auto_20180416_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=9),
            preserve_default=False,
        ),
    ]
