# Generated by Django 2.0.5 on 2018-05-29 18:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0032_auto_20180417_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
