# Generated by Django 2.0.6 on 2018-06-12 17:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0033_auto_20180529_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='is_equipment',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='part',
            name='refurbishment_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
