# Generated by Django 2.0.12 on 2019-03-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0037_part_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
