# Generated by Django 2.0.12 on 2019-04-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0039_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='parts.Part'),
            preserve_default=False,
        ),
    ]
