# Generated by Django 2.0.12 on 2019-04-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0040_revision_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='revision',
            name='revision_code',
            field=models.CharField(db_index=True, default='A', max_length=255),
        ),
    ]
