# Generated by Django 2.0.12 on 2019-04-16 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0041_auto_20190416_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='parts.Revision'),
        ),
    ]
