# Generated by Django 2.0.12 on 2019-04-24 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0043_auto_20190423_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
