# Generated by Django 2.0.12 on 2019-04-29 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0044_revision_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revision',
            options={'ordering': ['-created_at', '-revision_code']},
        ),
    ]
