# Generated by Django 2.0.12 on 2019-05-03 14:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0045_auto_20190429_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='custom_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
