# Generated by Django 2.0.12 on 2019-05-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedfields', '0001_initial'),
        ('parts', '0046_part_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='user_defined_fields',
            field=models.ManyToManyField(to='userdefinedfields.Field'),
        ),
    ]
