# Generated by Django 2.0.12 on 2019-05-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0047_part_user_defined_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='user_defined_fields',
            field=models.ManyToManyField(blank=True, to='userdefinedfields.Field'),
        ),
    ]
