# Generated by Django 2.0.12 on 2019-05-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0048_auto_20190514_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='user_defined_fields',
            field=models.ManyToManyField(blank=True, related_name='parts', to='userdefinedfields.Field'),
        ),
    ]
