# Generated by Django 2.2.4 on 2019-08-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0049_auto_20190521_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='is_equipment',
        ),
    ]
