// JavaScript source code
'use strict';
console.log('Running Delete Parts Test');

// Generated by Selenium IDE
const { Builder, By, Key, until, a, WebElement, promise } = require('selenium-webdriver');
const chrome = require('selenium-webdriver/chrome');
const assert = require('assert');
const chromedriver = require('chromedriver');

var driver;

(async function testParts() {

    driver = new Builder().forBrowser('chrome').build();

    // Step # | name | target | value
    // 1 | open | https://ooi-cgrdb-staging.whoi.net/ | 
    await driver.get("https://ooi-cgrdb-staging.whoi.net/");
    // 2 | setWindowSize | 1304x834 | 
    await driver.manage().window().setRect(1304, 834);
    // Set implict wait time in between steps
    await driver.manage().setTimeouts({ implicit: 4000 });

    try {

        // LOGIN
        await driver.findElement(By.linkText("Sign In")).click();
        await driver.findElement(By.id("id_login")).sendKeys("jkoch");
        await driver.findElement(By.id("id_password")).sendKeys("Automatedtests");
        await driver.findElement(By.css(".primaryAction")).click();

//      Delete Part Types, Part Templates and Inventory created running automated tests.
        // 10 | click | id=navbarTemplates |
        await driver.findElement(By.id("navbarTemplates")).click();
        await driver.findElement(By.id("navbarAdmintools")).click();
        // 5 | click | linkText=Test |
        await driver.findElement(By.linkText("Edit Part Types")).click();

        var i = 1;
        while (true) {
            if ((await driver.findElement(By.xpath("//tr[" + i + "]/td")).getText()) == "Sewing Machine") {
                break;
            } 
            i++;
        }

        await driver.findElement(By.css("tr:nth-child(" + i + ") .btn-danger")).click();
        // 6 | click | css=.btn-danger | 
        await driver.findElement(By.css(".btn-danger")).click();

        // 7 | click | id=navbarTemplates | 
        await driver.findElement(By.id("navbarTemplates")).click();
        // 8 | click | linkText=Parts | 
        await driver.findElement(By.linkText("Parts")).click();
        // 9 | click | id=searchbar-query | 
        await driver.findElement(By.id("searchbar-query")).click();
        // 10 | type | id=searchbar-query | Sewing Template
        await driver.findElement(By.id("searchbar-query")).sendKeys("Sewing Template");
        // 11 | click | css=.btn-outline-primary:nth-child(1) | 
        await driver.findElement(By.css(".btn-outline-primary:nth-child(1)")).click();
        // 12 | click | linkText=1232 | 
        await driver.findElement(By.linkText("1232")).click();
        // 13 | click | linkText=Delete | 
        await driver.findElement(By.linkText("Delete")).click();
        // 14 | click | css=.btn-danger | 
        await new Promise(r => setTimeout(r, 2000));
        await driver.findElement(By.css(".btn-danger")).click(); 


        // 15 | click | linkText=Inventory | 
        await driver.findElement(By.linkText("Inventory")).click();
        await new Promise(r => setTimeout(r, 4000));
        // Expand Test Location in Inventory Tree
        var j = (await driver.findElements(By.xpath(".//*[contains(text(),'Test')]/preceding-sibling::*"))).length + 1;
        await driver.findElement(By.xpath("//div/ul/li[" + j + "]/i")).click();    
        // Delete Sewing Template deletes it's Inventory
/*        await driver.wait(until.elementLocated(By.partialLinkText("sewing")));
        await driver.findElement(By.partialLinkText("sewing")).click();
        // 9 | click | linkText=Delete | 
        await driver.wait(until.elementLocated(By.linkText("Move to Trash")));
        await driver.findElement(By.linkText("Move to Trash")).click();
        // 10 | click | css=.btn-danger | 
        await new Promise(r => setTimeout(r, 2000));
        await driver.findElement(By.css(".btn-danger")).click */

        await new Promise(r => setTimeout(r, 2000));
        await driver.wait(until.elementLocated(By.partialLinkText("PIONEER INSHORE DECK")));
        await driver.findElement(By.partialLinkText("PIONEER INSHORE DECK")).click();
        // 9 | click | linkText=Delete | 
        await driver.wait(until.elementLocated(By.linkText("Move to Trash")));
        await driver.findElement(By.linkText("Move to Trash")).click();
        // 10 | click | css=.btn-danger | 
        await new Promise(r => setTimeout(r, 2000));
        await driver.findElement(By.css(".btn-danger")).click();


    }
    catch (e) {
        console.log(e.message, e.stack);
        console.log("Delete Parts failed.");
        throw (e);
    } 

    console.log("Delete Parts completed.")
    return;

})();
