# Generated by Django 2.2.4 on 2019-10-14 14:48

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(blank=True, choices=[('Array', 'Array'), ('Mooring', 'Mooring'), ('Instrument', 'Instrument')], max_length=20)),
                ('location_id', models.CharField(blank=True, max_length=100)),
                ('weight', models.IntegerField(blank=True, default=0, null=True)),
                ('root_type', models.CharField(blank=True, choices=[('Land', 'Land'), ('Sea', 'Sea'), ('Retired', 'Retired'), ('Snapshots', 'Snapshots'), ('Trash', 'Trash')], max_length=20)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='locations.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
