# Generated by Django 2.0 on 2017-12-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20171212_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, choices=[('Array', 'Array'), ('Mooring', 'Mooring'), ('Node', 'Node'), ('Assembly', 'Assembly')], max_length=20, null=True),
        ),
    ]
