# Generated by Django 2.2.4 on 2019-10-23 15:13
"""
Auto-generate default Root locations for start up
"""
from django.db import migrations
from django.apps import apps

Location = apps.get_model('locations', 'Location')

def create_root_locations(apps, schema_editor):
    land, created = Location.objects.get_or_create(name='Land')
    if created:
        land.root_type = 'Land'
        land.save()

    sea, created = Location.objects.get_or_create(name='Sea')
    if created:
        sea.root_type = 'Sea'
        sea.save()

    retired, created = Location.objects.get_or_create(name='Retired')
    if created:
        retired.root_type = 'Retired'
        retired.weight = 500
        retired.save()

    trash, created = Location.objects.get_or_create(name='Trash Bin')
    if created:
        trash.root_type = 'Trash'
        trash.weight = 1000
        trash.save()


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20191023_1405'),
    ]

    operations = [
        migrations.RunPython(create_root_locations),
    ]
