"""
# Copyright (C) 2019-2020 Woods Hole Oceanographic Institution
#
# This file is part of the Roundabout Database project ("RDB" or
# "ooicgsn-roundabout").
#
# ooicgsn-roundabout is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# ooicgsn-roundabout is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ooicgsn-roundabout in the COPYING.md file at the project root.
# If not, see <http://www.gnu.org/licenses/>.
"""

# Generated by Django 2.2.4 on 2019-10-23 15:13
"""
Auto-generate default Root locations for start up
"""
from django.db import migrations
from django.apps import apps
from mptt import register, managers


def create_root_locations(apps, schema_editor):
    Location = apps.get_model('locations', 'Location')

    manager = managers.TreeManager()
    manager.model = Location

    register(Location)
    manager.contribute_to_class(Location, 'objects')

    land, created = Location.objects.get_or_create(name='Land')
    if created:
        land.root_type = 'Land'
        land.save()

    sea, created = Location.objects.get_or_create(name='Sea')
    if created:
        sea.root_type = 'Sea'
        sea.save()

    retired, created = Location.objects.get_or_create(name='Retired')
    if created:
        retired.root_type = 'Retired'
        retired.weight = 500
        retired.save()

    trash, created = Location.objects.get_or_create(name='Trash Bin')
    if created:
        trash.root_type = 'Trash'
        trash.weight = 1000
        trash.save()


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20191023_1405'),
    ]

    operations = [
        migrations.RunPython(create_root_locations),
    ]
