# Generated by Django 3.0.10 on 2020-10-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20200821_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
