# Generated by Django 2.0 on 2018-01-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20171213_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, choices=[('Array', 'Array'), ('Mooring', 'Mooring'), ('Node', 'Node'), ('Assembly', 'Assembly')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
