# Generated by Django 2.0.6 on 2018-08-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20180122_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, choices=[('Array', 'Array'), ('Mooring', 'Mooring')], max_length=20),
        ),
    ]
