# Generated by Django 2.0.6 on 2018-09-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20180808_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
