# Generated by Django 2.0.6 on 2018-09-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_location_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
