# Generated by Django 2.0.12 on 2019-05-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20180912_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, choices=[('Array', 'Array'), ('Mooring', 'Mooring'), ('Instrument', 'Instrument')], max_length=20),
        ),
    ]
