# Generated by Django 2.2.1 on 2019-05-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20190523_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='root_type',
            field=models.CharField(blank=True, choices=[('Land', 'Land'), ('Sea', 'Sea'), ('Retired', 'Retired'), ('Snapshots', 'Snapshots'), ('Trash', 'Trash')], max_length=20),
        ),
    ]
