# Generated by Django 2.0 on 2018-01-05 15:57

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20171213_1818'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_number', models.CharField(max_length=255, unique=True)),
                ('location', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment', to='locations.Location')),
            ],
            options={
                'ordering': ['deployment_number'],
            },
        ),
    ]
