# Generated by Django 2.2.9 on 2020-02-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20191023_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('invadd', 'Add Inventory'), ('invchange', 'Inventory Change'), ('locationchange', 'Location Change'), ('subchange', 'Subassembly Change'), ('addtobuild', 'Add to Build'), ('removefrombuild', 'Remove from Build'), ('deploymentburnin', 'Deployment Burnin'), ('deploymenttosea', 'Deployment to Field'), ('deploymentupdate', 'Deployment Update'), ('deploymentrecover', 'Deployment Recovered'), ('assigndest', 'Assign Destination'), ('removedest', 'Remove Destination'), ('test', 'Test'), ('note', 'Note'), ('historynote', 'Historical Note'), ('ticket', 'Work Ticket'), ('fieldchange', 'Field Change'), ('flag', 'Flag'), ('movetotrash', 'Move to Trash')], max_length=20),
        ),
        migrations.AlterField(
            model_name='deploymentaction',
            name='action_type',
            field=models.CharField(choices=[('deploy', 'Deployed to Field'), ('recover', 'Recovered from Field'), ('retire', 'Retired'), ('create', 'Created'), ('burnin', 'Burn In'), ('details', 'Deployment Details')], max_length=20),
        ),
    ]
