# Generated by Django 2.0 on 2018-01-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_deployment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='deployment_number',
            field=models.CharField(max_length=255),
        ),
    ]
