# Generated by Django 2.0 on 2018-01-22 15:26

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20180118_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='location',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment', to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='part',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='parts.Part'),
        ),
    ]
