# Generated by Django 2.2.10 on 2020-04-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200302_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at', 'action_type']},
        ),
        migrations.AlterModelOptions(
            name='deploymentaction',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at', 'action_type']},
        ),
    ]
