# Generated by Django 2.2.10 on 2020-04-30 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0011_auto_20200309_1601'),
        ('inventory', '0006_auto_20200424_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action', to='builds.Build'),
        ),
        migrations.AddField(
            model_name='action',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action', to='inventory.Deployment'),
        ),
    ]
