# Generated by Django 2.0 on 2018-01-24 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0006_auto_20180122_1529'),
        ('inventory', '0007_auto_20180122_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('INVCHANGE', 'Inventory Change'), ('SUBCHANGE', 'Subassembly Change'), ('TEST', 'Test'), ('NOTE', 'Note'), ('TICKET', 'Work Ticket'), ('FLAG', 'Flag')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detail', models.TextField(blank=True)),
                ('location', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action', to='locations.Location')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'action_type'],
            },
        ),
    ]
