# Generated by Django 2.0 on 2018-01-24 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action', to='inventory.Inventory'),
        ),
    ]
