# Generated by Django 2.2.10 on 2020-05-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20200430_1633'),
        ('inventory', '0007_auto_20200430_1846'),
    ]

    operations = [
    ]
