# Generated by Django 2.0 on 2018-01-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_action_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='flag',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='test_result',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='test_type',
            field=models.CharField(blank=True, choices=[('INCOMING', 'Incoming Test'), ('OUTGOING', 'Outgoing Test')], max_length=20),
        ),
    ]
