# Generated by Django 2.2.10 on 2020-05-01 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_merge_20200501_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action', to='inventory.Inventory'),
        ),
    ]
