# Generated by Django 2.2.10 on 2020-05-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20200501_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_actions', to='builds.Build'),
        ),
        migrations.AlterField(
            model_name='action',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_actions', to='inventory.Deployment'),
        ),
        migrations.AlterField(
            model_name='action',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_actions', to='inventory.Inventory'),
        ),
    ]
