# Generated by Django 2.0 on 2018-01-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20180124_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='test_result',
            field=models.NullBooleanField(),
        ),
    ]
