# Generated by Django 2.0 on 2018-01-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20180124_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('invchange', 'Inventory Change'), ('subchange', 'Subassembly Change'), ('test', 'Test'), ('note', 'Note'), ('ticket', 'Work Ticket'), ('flag', 'Flag')], max_length=20),
        ),
    ]
