# Generated by Django 2.0 on 2018-01-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20180129_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='test_result',
            field=models.NullBooleanField(choices=[(None, '-'), (True, 'Pass'), (False, 'Fail')]),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='test_type',
            field=models.CharField(choices=[('incoming', 'Incoming Test'), ('outgoing', 'Outgoing Test')], max_length=20),
        ),
    ]
