# Generated by Django 2.0 on 2018-01-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20180131_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at', 'action_type']},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='flag',
            field=models.BooleanField(choices=[(True, 'Flagged'), (False, 'Unflagged')], default=False),
        ),
    ]
