# Generated by Django 2.0 on 2018-01-31 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20180131_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-created_at', 'action_type']},
        ),
    ]
