# Generated by Django 2.2.10 on 2020-05-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20200513_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='node_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
