# Generated by Django 2.0 on 2018-02-28 16:27

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20180122_1529'),
        ('inventory', '0016_auto_20180205_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='final_location',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_deployment', to='locations.Location'),
        ),
    ]
