# Generated by Django 2.2.10 on 2020-05-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_action_node_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='node_type',
            new_name='object_type',
        ),
    ]
