# Generated by Django 2.0 on 2018-03-22 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_deployment_final_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='parts.Part'),
        ),
    ]
