# Generated by Django 2.0 on 2018-04-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20180322_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
