# Generated by Django 2.0 on 2018-04-18 14:28

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('moorings', '0001_initial'),
        ('inventory', '0019_auto_20180409_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='mooring_part',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='moorings.MooringPart'),
        ),
    ]
