# Generated by Django 2.2.10 on 2020-05-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20200522_1822'),
    ]

    operations = [
    ]
