# Generated by Django 2.2.10 on 2020-05-22 18:24

from django.apps import apps
from django.db import migrations

DeploymentAction = apps.get_model('inventory', 'DeploymentAction')

def update_deployment_actions(apps, schema_editor):
    for action in DeploymentAction.objects.all():
        if action.action_type == 'create':
            action.action_type = 'startdeployment'
            action.save()
        elif action.action_type == 'burnin':
            action.action_type = 'deploymentburnin'
            action.save()
        elif action.action_type == 'deploy':
            action.action_type = 'deploymenttosea'
            action.save()
        elif action.action_type == 'recover':
            action.action_type = 'deploymentrecover'
            action.save()
        elif action.action_type == 'retire':
            action.action_type = 'deploymentretire'
            action.save()
        elif action.action_type == 'details':
            action.action_type = 'deploymentdetails'
            action.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20200522_1822'),
    ]

    operations = [
        migrations.RunPython(update_deployment_actions),
    ]
