# Generated by Django 2.0 on 2018-04-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_inventory_mooring_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='test_type',
            field=models.CharField(blank=True, choices=[('incoming', 'Incoming Test'), ('outgoing', 'Outgoing Test')], max_length=20, null=True),
        ),
    ]
