# Generated by Django 2.0 on 2018-05-09 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20180419_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
