# Generated by Django 2.2.10 on 2020-05-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20200523_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='deployment_type',
            field=models.CharField(blank=True, choices=[('build_deployment', 'Build Deployment'), ('inventory_deployment', 'Inventory Deployment')], max_length=20, null=True),
        ),
    ]
