# Generated by Django 2.0 on 2018-05-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_deployment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('invadd', 'Add Inventory'), ('invchange', 'Inventory Change'), ('subchange', 'Subassembly Change'), ('test', 'Test'), ('note', 'Note'), ('ticket', 'Work Ticket'), ('flag', 'Flag')], max_length=20),
        ),
    ]
