# Generated by Django 2.2.10 on 2020-05-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_action_deployment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='deployment_type',
            field=models.CharField(blank=True, choices=[('build_deployment', 'Build Deployment'), ('inventory_deployment', 'Inventory Deployment')], default='', max_length=20),
        ),
    ]
