# Generated by Django 2.2.10 on 2020-05-28 15:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0008_auto_20200513_1525'),
        ('inventory', '0023_auto_20200527_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='deployment',
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('invadd', 'Add Inventory'), ('invchange', 'Inventory Change'), ('locationchange', 'Location Change'), ('subchange', 'Sub-Assembly Change'), ('addtobuild', 'Add to Build'), ('removefrombuild', 'Remove from Build'), ('startdeployment', 'Start Deployment'), ('deploymentburnin', 'Deployment Burnin'), ('deploymenttosea', 'Deployment to Field'), ('deploymentupdate', 'Deployment Update'), ('deploymentrecover', 'Deployment Recovery'), ('deploymentretire', 'Deployment Retired'), ('deploymentdetails', 'Deployment Details Updated'), ('assigndest', 'Assign Destination'), ('removedest', 'Remove Destination'), ('test', 'Test'), ('note', 'Note'), ('historynote', 'Historical Note'), ('ticket', 'Work Ticket'), ('fieldchange', 'Field Change'), ('flag', 'Flag'), ('movetotrash', 'Move to Trash')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='InventoryDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deployment_burnin_date', models.DateTimeField(blank=True, null=True)),
                ('deployment_to_field_date', models.DateTimeField(blank=True, null=True)),
                ('deployment_recovery_date', models.DateTimeField(blank=True, null=True)),
                ('deployment_retire_date', models.DateTimeField(blank=True, null=True)),
                ('time_at_sea', models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
                ('cruise_deployed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_deployments', to='cruises.Cruise')),
                ('cruise_recovered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_inventory_deployments', to='cruises.Cruise')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_deployments', to='inventory.Deployment')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_deployments', to='inventory.Inventory')),
            ],
            options={
                'ordering': ['-deployment_start_date'],
                'get_latest_by': 'deployment_start_date',
            },
        ),
    ]
