# Generated by Django 2.0.5 on 2018-05-24 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20180509_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
