# Generated by Django 2.0.5 on 2018-05-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20180524_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
