# Generated by Django 2.2.10 on 2020-05-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20200528_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydeployment',
            name='current_status',
            field=models.CharField(choices=[('startdeployment', 'Start Deployment'), ('deploymentburnin', 'Deployment Burnin'), ('deploymenttosea', 'Deployment to Field'), ('deploymentrecover', 'Deployment Recovery'), ('deploymentretire', 'Deployment Retired')], db_index=True, default='startdeployment', max_length=20),
        ),
    ]
