# Generated by Django 2.2.10 on 2020-05-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_inventorydeployment_current_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorydeployment',
            name='time_at_sea',
        ),
    ]
