# Generated by Django 2.0.5 on 2018-06-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20180529_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='old_serial_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
