# Generated by Django 2.2.10 on 2020-05-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_remove_inventorydeployment_time_at_sea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydeployment',
            name='current_status',
            field=models.CharField(choices=[('startdeployment', 'Start Deployment'), ('deploymentburnin', 'Deployment Burnin'), ('deploymenttofield', 'Deployment to Field'), ('deploymentrecover', 'Deployment Recovery'), ('deploymentretire', 'Deployment Retired')], db_index=True, default='startdeployment', max_length=20),
        ),
    ]
