# Generated by Django 2.0.6 on 2018-06-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_inventory_old_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='ooi_property_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventory',
            name='whoi_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('invadd', 'Add Inventory'), ('invchange', 'Inventory Change'), ('subchange', 'Subassembly Change'), ('test', 'Test'), ('note', 'Note'), ('historynote', 'Historical Note'), ('ticket', 'Work Ticket'), ('flag', 'Flag')], max_length=20),
        ),
    ]
