# Generated by Django 2.2.10 on 2020-05-29 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20200529_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='inventory_deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='inventory.InventoryDeployment'),
        ),
    ]
