# Generated by Django 2.2.10 on 2020-05-29 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_action_inventory_deployment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deployment',
            options={'get_latest_by': 'deployment_start_date', 'ordering': ['build', '-deployment_start_date']},
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='deployment',
            name='current_status',
            field=models.CharField(choices=[('startdeployment', 'Start Deployment'), ('deploymentburnin', 'Deployment Burnin'), ('deploymenttofield', 'Deployment to Field'), ('deploymentrecover', 'Deployment Recovery'), ('deploymentretire', 'Deployment Retired')], db_index=True, default='startdeployment', max_length=20),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deployment_burnin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deployment_recovery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deployment_retire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deployment_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deployment_to_field_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
