# Generated by Django 2.0.6 on 2018-08-16 14:01

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('moorings', '0006_auto_20180808_0951'),
        ('inventory', '0028_auto_20180808_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='future_destination',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_destination', to='moorings.MooringPart'),
        ),
    ]
