# Generated by Django 2.0.6 on 2018-08-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_inventory_future_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='future_destination',
        ),
    ]
