# Generated by Django 2.2.10 on 2020-05-29 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_auto_20200529_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='depth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='deployment',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(0)]),
        ),
    ]
