# Generated by Django 2.0.6 on 2018-09-10 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20180808_0951'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0030_remove_inventory_future_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('deploy', 'Deploy to Sea'), ('recover', 'Recover from Sea'), ('retire', 'Retire')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('detail', models.TextField(blank=True)),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment_action', to='inventory.Deployment')),
                ('location', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_action', to='locations.Location')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_action', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'action_type'],
            },
        ),
    ]
