# Generated by Django 2.2.10 on 2020-05-30 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_20200529_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deployment',
            options={'get_latest_by': 'deployment_start_date', 'ordering': ['-deployment_start_date']},
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='assembly',
        ),
        migrations.AlterField(
            model_name='deployment',
            name='cruise_deployed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment', to='cruises.Cruise'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='cruise_recovered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_deployment', to='cruises.Cruise'),
        ),
        migrations.AlterField(
            model_name='inventorydeployment',
            name='cruise_deployed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventorydeployment', to='cruises.Cruise'),
        ),
        migrations.AlterField(
            model_name='inventorydeployment',
            name='cruise_recovered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_inventorydeployment', to='cruises.Cruise'),
        ),
    ]
