# Generated by Django 2.0.6 on 2018-09-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_deploymentaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentaction',
            name='action_type',
            field=models.CharField(choices=[('deploy', 'Deploy to Sea'), ('recover', 'Recover from Sea'), ('retire', 'Retire'), ('create', 'Create')], max_length=20),
        ),
    ]
