# Generated by Django 2.0.6 on 2018-09-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_auto_20180912_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentaction',
            name='action_type',
            field=models.CharField(choices=[('deploy', 'Deploy to Sea'), ('recover', 'Recover from Sea'), ('retire', 'Retire'), ('create', 'Create'), ('burnin', 'Burn In')], max_length=20),
        ),
    ]
