# Generated by Django 2.2.10 on 2020-05-31 18:18

from django.apps import apps
from django.db import migrations




class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_auto_20200530_1349'),
    ]

    operations = [
    ]
