# Generated by Django 2.0.6 on 2018-09-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_auto_20180918_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentaction',
            name='action_type',
            field=models.CharField(choices=[('deploy', 'Deployed to Sea'), ('recover', 'Recovered from Sea'), ('retire', 'Retired'), ('create', 'Created'), ('burnin', 'Burn In')], max_length=20),
        ),
    ]
