# Generated by Django 2.2.13 on 2020-06-10 17:35
from django.apps import apps
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_auto_20200610_1734'),
    ]

    operations = [
    ]
