# Generated by Django 2.0.6 on 2018-09-18 17:06

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20180912_1356'),
        ('inventory', '0035_inventorysnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment_snapshot', to='inventory.Deployment')),
                ('location', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_snapshot', to='locations.Location')),
            ],
        ),
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshot', to='inventory.DeploymentSnapshot'),
        ),
    ]
