# Generated by Django 2.2.13 on 2020-06-11 18:22

from django.apps import apps
from django.db import migrations

Action = apps.get_model('inventory', 'Action')

# Update Inventory Actions to new "ADD" type
def update_inv_actions(apps, schema_editor):
    actions = Action.objects.all()

    for action in actions:
        if action.action_type == 'invadd':
            action.action_type = 'add'
        action.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_auto_20200611_1821'),
    ]

    operations = [
        migrations.RunPython(update_inv_actions),
    ]
