# Generated by Django 2.2.13 on 2020-06-11 18:22

from django.apps import apps
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_auto_20200611_1821'),
    ]

    operations = [

    ]
