# Generated by Django 2.0.6 on 2018-09-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_auto_20180918_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsnapshot',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
