# Generated by Django 2.0.6 on 2018-09-19 17:09

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20180912_1356'),
        ('inventory', '0037_deploymentsnapshot_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsnapshot',
            name='snapshot_location',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_snapshot_location', to='locations.Location'),
        ),
    ]
