# Generated by Django 2.2.13 on 2020-06-23 20:29


from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_auto_20200618_1441'),
    ]

    operations = [
    ]
