# Generated by Django 2.2.13 on 2020-06-23 20:29

from django.apps import apps
from django.db import migrations

Inventory = apps.get_model('inventory', 'Inventory')
Build = apps.get_model('builds', 'Build')
BuildAction = apps.get_model('builds', 'BuildAction')
Action = apps.get_model('inventory', 'Action')

# Update Build action_types
def update_builds_actions(apps, schema_editor):
    actions = BuildAction.objects.all()

    for action in actions:
        if action.action_type == 'subassemblychange':
            action.action_type = 'subchange'
        elif action.action_type == 'buildadd':
            action.action_type = 'add'
        elif action.action_type == 'deploymenttosea':
            action.action_type = 'deploymenttofield'
        action.save()


# Import old BuildAction objs to Actioon
def import_old_actions(apps, schema_editor):
    actions = BuildAction.objects.all()
    for action in actions:
        new_action = Action.objects.create(
            build=action.build,
            action_type=action.action_type,
            object_type='build',
            location=action.location,
            created_at=action.created_at,
            detail=action.detail,
            user=action.user,
        )

# Update legacy Inventory Actions to add Build/Parent metadata
def update_inv_actions(apps, schema_editor):
    items = Inventory.objects.all()

    for item in items:
        last_action = item.actions.latest()

        if item.build:
            last_action.build = item.build

        if item.parent:
            last_action.parent = item.parent

        last_action.save()

# Update legacy Build Actions if they're Deployment actions
def update_build__dep_actions(apps, schema_editor):
    builds = Build.objects.all()
    dep_action_list = ['startdeployment', 'deploymentburnin', 'deploymenttofield', 'deploymentdetails', 'deploymentrecover', 'deploymentretire']
    for build in builds:
        actions = build.get_actions()
        dep_actions = actions.filter(action_type__in=dep_action_list)
        for action in dep_actions:
            action.deployment_type = 'build_deployment'
            action.deployment = build.get_latest_deployment()
            action.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_auto_20200618_1441'),
    ]

    operations = [
        migrations.RunPython(update_build_actions),
        migrations.RunPython(import_old_actions),
        migrations.RunPython(update_inv_actions),
        migrations.RunPython(update_build__dep_actions),
    ]
