# Generated by Django 2.0.6 on 2018-09-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_deploymentsnapshot_snapshot_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deploymentsnapshot',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='order',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
