# Generated by Django 2.2.13 on 2020-07-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_auto_20200623_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='object_type',
            field=models.CharField(blank=True, choices=[('build', 'Build'), ('inventory', 'Inventory'), ('deployment', 'Deployment'), ('calibration_event', 'Calibration Event')], db_index=True, max_length=20),
        ),
    ]
