# Generated by Django 2.2.13 on 2020-07-08 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0014_auto_20200625_1324'),
        ('inventory', '0040_auto_20200708_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='calibration_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='calibrations.CalibrationEvent'),
        ),
    ]
