# Generated by Django 2.0.6 on 2018-09-28 17:47

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_auto_20180926_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='assigned_destination_root',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_children', to='inventory.Inventory'),
        ),
    ]
