# Generated by Django 2.0.6 on 2018-10-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_inventory_assigned_destination_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
