# Generated by Django 2.0.6 on 2018-10-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_action_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='photo',
        ),
        migrations.AddField(
            model_name='photonote',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='inventory.Action'),
        ),
    ]
