# Generated by Django 2.2.13 on 2020-07-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs_constants', '0011_auto_20200716_1806'),
        ('inventory', '0045_auto_20200715_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='config_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='configs_constants.ConfigEvent'),
        ),
        migrations.AlterField(
            model_name='action',
            name='object_type',
            field=models.CharField(blank=True, choices=[('build', 'Build'), ('inventory', 'Inventory'), ('deployment', 'Deployment'), ('calibrationevent', 'Calibration Event'), ('constdefaultevent', 'Constant Default Event'), ('configevent', 'Configuration/Constant Event')], db_index=True, max_length=20),
        ),
    ]
