# Generated by Django 2.0.6 on 2018-10-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_auto_20181024_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photonote',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='inventory.Action'),
        ),
        migrations.AlterField(
            model_name='photonote',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
