# Generated by Django 2.0.6 on 2018-10-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_auto_20181024_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photonote',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='inventory.Action'),
        ),
    ]
