# Generated by Django 2.2.13 on 2020-07-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs_constants', '0013_configdefault_configdefaultevent'),
        ('inventory', '0046_auto_20200717_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='config_default_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='configs_constants.ConfigDefaultEvent'),
        ),
        migrations.AlterField(
            model_name='action',
            name='object_type',
            field=models.CharField(blank=True, choices=[('build', 'Build'), ('inventory', 'Inventory'), ('deployment', 'Deployment'), ('calibrationevent', 'Calibration Event'), ('constdefaultevent', 'Constant Default Event'), ('configevent', 'Configuration/Constant Event'), ('configdefaultevent', 'Configuration Default Event')], db_index=True, max_length=20),
        ),
    ]
