# Generated by Django 2.2.13 on 2020-07-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_auto_20200723_1620'),
    ]

    operations = [
    ]
