# Generated by Django 2.0.6 on 2018-10-24 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_auto_20181024_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='photonote',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='inventory.Inventory'),
        ),
    ]
