# Generated by Django 2.2.13 on 2020-08-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0018_auto_20200812_1515'),
        ('inventory', '0047_auto_20200723_1620_squashed_0048_auto_20200727_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='coefficient_name_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='calibrations.CoefficientNameEvent'),
        ),
        migrations.AlterField(
            model_name='action',
            name='object_type',
            field=models.CharField(blank=True, choices=[('build', 'Build'), ('inventory', 'Inventory'), ('deployment', 'Deployment'), ('calibrationevent', 'Calibration Event'), ('constdefaultevent', 'Constant Default Event'), ('configevent', 'Configuration/Constant Event'), ('configdefaultevent', 'Configuration Default Event'), ('coefficientnameevent', 'Coefficient Name Event')], db_index=True, max_length=20),
        ),
    ]
