# Generated by Django 2.2.13 on 2020-08-17 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs_constants', '0015_auto_20200817_1747'),
        ('inventory', '0048_auto_20200812_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='config_name_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='configs_constants.ConfigNameEvent'),
        ),
        migrations.AlterField(
            model_name='action',
            name='object_type',
            field=models.CharField(blank=True, choices=[('build', 'Build'), ('inventory', 'Inventory'), ('deployment', 'Deployment'), ('calibrationevent', 'Calibration Event'), ('constdefaultevent', 'Constant Default Event'), ('configevent', 'Configuration/Constant Event'), ('configdefaultevent', 'Configuration Default Event'), ('coefficientnameevent', 'Coefficient Name Event'), ('confignameevent', 'Configuration Name Event')], db_index=True, max_length=20),
        ),
    ]
