# Generated by Django 2.2.13 on 2020-08-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_auto_20200801_1854'),
        ('inventory', '0049_auto_20200817_2123'),
    ]

    operations = [
    ]
