# Generated by Django 2.0.9 on 2018-12-13 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_auto_20181213_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='time_at_sea',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
