# Generated by Django 2.0.12 on 2019-04-24 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0043_auto_20190423_1503'),
        ('inventory', '0051_inventory_time_at_sea'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='parts.Revision'),
        ),
    ]
