# Generated by Django 2.2.13 on 2020-09-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_auto_20200923_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='time_at_sea',
            new_name='_time_at_sea',
        ),
    ]
