# Generated by Django 2.2.13 on 2020-09-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_auto_20200923_1919'),
        ('inventory', '0050_merge_20200819_1340'),
    ]

    operations = [
    ]
