# Generated by Django 2.2.13 on 2020-09-28 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_auto_20200923_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)]),
        ),
    ]
