# Generated by Django 2.2.13 on 2020-09-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_merge_20200925_1748'),
        ('inventory', '0053_auto_20200928_1821'),
    ]

    operations = [
    ]
