# Generated by Django 3.1.3 on 2020-11-23 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0011_auto_20201117_2030'),
        ('inventory', '0055_auto_20201014_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydeployment',
            name='assembly_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_deployments', to='assemblies.assemblypart'),
        ),
    ]
