# Generated by Django 3.1.3 on 2020-12-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_inventorydeployment_assembly_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydeployment',
            name='item_depth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
