# Generated by Django 2.0.12 on 2019-05-06 13:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_auto_20190501_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='custom_field_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
