# Generated by Django 3.1.3 on 2021-01-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_inventorydeployment_item_depth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorydeployment',
            name='item_depth',
        ),
    ]
