# Generated by Django 3.1.3 on 2021-02-04 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_auto_20210112_1924'),
        ('inventory', '0057_inventoryhyperlink'),
    ]

    operations = [
    ]
