# Generated by Django 2.0.12 on 2019-05-21 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0058_auto_20190516_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='parts.Part'),
        ),
    ]
