# Generated by Django 3.1.3 on 2021-02-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0058_merge_20210204_2227'),
        ('inventory', '0059_merge_20210203_1541'),
    ]

    operations = [
    ]
