# Generated by Django 2.2.1 on 2019-05-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_auto_20190521_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photonote',
            name='photo',
            field=models.FileField(upload_to='photos/'),
        ),
    ]
