# Generated by Django 3.1.3 on 2021-03-03 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0060_merge_20210209_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='user_approver',
            field=models.ManyToManyField(related_name='deployments_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deployment',
            name='user_draft',
            field=models.ManyToManyField(blank=True, related_name='deployments_reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
