# Generated by Django 2.2.1 on 2019-05-28 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0060_auto_20190528_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photonote',
            name='photo',
            field=models.FileField(upload_to='photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg', 'gif'])]),
        ),
    ]
