# Generated by Django 3.1.3 on 2021-03-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0061_auto_20210303_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='approved',
            field=models.BooleanField(choices=[(True, 'Approved'), (False, 'Draft')], default=False),
        ),
    ]
