# Generated by Django 2.2.1 on 2019-06-12 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0062_auto_20190528_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentsnapshot',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
