# Generated by Django 3.1.3 on 2021-03-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0062_deployment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
