# Generated by Django 2.2.1 on 2019-06-19 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0005_assembly_assembly_type'),
        ('inventory', '0063_auto_20190612_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='assembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='assemblies.Assembly'),
        ),
    ]
