# Generated by Django 2.2.1 on 2019-06-19 16:25

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_deployment_assembly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='assemblies.Assembly'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='final_location',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_deployment', to='locations.Location'),
        ),
    ]
