# Generated by Django 3.1.3 on 2021-04-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_action_location_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='object_type',
            field=models.CharField(blank=True, choices=[('build', 'Build'), ('inventory', 'Inventory'), ('deployment', 'Deployment'), ('calibrationevent', 'Calibration Event'), ('constdefaultevent', 'Constant Default Event'), ('configevent', 'Configuration/Constant Event'), ('configdefaultevent', 'Configuration Default Event'), ('coefficientnameevent', 'Coefficient Name Event'), ('confignameevent', 'Configuration Name Event'), ('location', 'Location')], db_index=True, max_length=20),
        ),
    ]
