# Generated by Django 3.1.3 on 2021-04-27 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0019_merge_20210209_1909'),
        ('inventory', '0065_auto_20210424_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='cruises.vessel'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('add', 'Added to RDB'), ('update', 'Details updated'), ('locationchange', 'Location Change'), ('subchange', 'Sub-Assembly Change'), ('addtobuild', 'Add to Build'), ('removefrombuild', 'Remove from Build'), ('startdeployment', 'Start Deployment'), ('removefromdeployment', 'Deployment Ended'), ('deploymentburnin', 'Deployment Burnin'), ('deploymenttofield', 'Deployment to Field'), ('deploymentupdate', 'Deployment Update'), ('deploymentrecover', 'Deployment Recovery'), ('deploymentretire', 'Deployment Retired'), ('deploymentdetails', 'Deployment Details Updated'), ('assigndest', 'Assign Destination'), ('removedest', 'Remove Destination'), ('test', 'Test'), ('note', 'Note'), ('historynote', 'Historical Note'), ('ticket', 'Work Ticket'), ('fieldchange', 'Field Change'), ('flag', 'Flag'), ('movetotrash', 'Move to Trash'), ('retirebuild', 'Retire Build'), ('reviewapprove', 'Reviewer approved Event'), ('reviewunapprove', 'Reviewer unapproved Event'), ('eventapprove', 'Event Approved'), ('eventunapprove', 'Event Unapproved'), ('calcsvimport', 'Calibration CSV Uploaded'), ('calcsvupdate', 'Updated by Calibration CSV')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='action',
            name='object_type',
            field=models.CharField(blank=True, choices=[('build', 'Build'), ('inventory', 'Inventory'), ('deployment', 'Deployment'), ('calibrationevent', 'Calibration Event'), ('constdefaultevent', 'Constant Default Event'), ('configevent', 'Configuration/Constant Event'), ('configdefaultevent', 'Configuration Default Event'), ('coefficientnameevent', 'Coefficient Name Event'), ('confignameevent', 'Configuration Name Event'), ('location', 'Location'), ('vessel', 'Vessel'), ('cruise', 'Cruise')], db_index=True, max_length=20),
        ),
    ]
