# Generated by Django 3.1.3 on 2021-04-28 15:09

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_remove_location_location_type'),
        ('inventory', '0065_auto_20210424_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='location',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='locations.location'),
        ),
    ]
