# Generated by Django 2.2.1 on 2019-06-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_build_build_notes'),
        ('inventory', '0065_auto_20190619_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='builds.Build'),
        ),
    ]
