# Generated by Django 3.1.3 on 2021-04-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0066_auto_20210427_1747'),
        ('inventory', '0066_auto_20210428_1509'),
    ]

    operations = [
    ]
