# Generated by Django 3.1.3 on 2021-06-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0067_merge_20210429_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhyperlink',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
