# Generated by Django 3.1.3 on 2021-05-12 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0067_merge_20210429_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='user_approver',
            field=models.ManyToManyField(related_name='approver_deployments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='user_draft',
            field=models.ManyToManyField(blank=True, related_name='reviewer_deployments', to=settings.AUTH_USER_MODEL),
        ),
    ]
