# Generated by Django 2.2.1 on 2019-06-28 16:15

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0067_deployment_build'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='final_location',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_deployments', to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='location',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='locations.Location'),
        ),
    ]
