# Generated by Django 3.1.3 on 2021-06-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0068_auto_20210609_0619'),
        ('inventory', '0068_auto_20210512_1446'),
    ]

    operations = [
    ]
