# Generated by Django 3.1.3 on 2021-06-07 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0009_auto_20210603_1622'),
        ('inventory', '0068_auto_20210512_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='reference_designator_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='ooi_ci_tools.referencedesignatorevent'),
        ),
        migrations.AlterField(
            model_name='action',
            name='object_type',
            field=models.CharField(blank=True, choices=[('build', 'Build'), ('inventory', 'Inventory'), ('deployment', 'Deployment'), ('calibrationevent', 'Calibration Event'), ('constdefaultevent', 'Constant Default Event'), ('configevent', 'Configuration/Constant Event'), ('configdefaultevent', 'Configuration Default Event'), ('coefficientnameevent', 'Coefficient Name Event'), ('confignameevent', 'Configuration Name Event'), ('location', 'Location'), ('vessel', 'Vessel'), ('cruise', 'Cruise'), ('referencedesignatorevent', 'Reference Designator Event')], db_index=True, max_length=25),
        ),
    ]
