# Generated by Django 2.2.1 on 2019-07-01 16:57

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0005_assembly_assembly_type'),
        ('inventory', '0068_auto_20190628_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='assembly_part',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='assemblies.AssemblyPart'),
        ),
    ]
