# Generated by Django 3.1.3 on 2021-06-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0069_merge_20210610_1728'),
        ('inventory', '0069_auto_20210607_1910'),
    ]

    operations = [
    ]
