# Generated by Django 3.1.3 on 2021-09-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0070_merge_20210611_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='object_type',
            field=models.CharField(blank=True, choices=[('build', 'Build'), ('inventory', 'Inventory'), ('deployment', 'Deployment'), ('calibrationevent', 'Calibration Event'), ('constdefaultevent', 'Constant Default Event'), ('configevent', 'Configuration/Constant Event'), ('configdefaultevent', 'Configuration Default Event'), ('coefficientnameevent', 'Coefficient Name Event'), ('confignameevent', 'Configuration Name Event'), ('location', 'Location'), ('vessel', 'Vessel'), ('cruise', 'Cruise'), ('referencedesignatorevent', 'Reference Designator Event'), ('bulkuploadevent', 'Bulk Upload Event')], db_index=True, max_length=25),
        ),
    ]
