# Generated by Django 3.1.3 on 2021-09-27 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0019_auto_20210915_1506'),
        ('inventory', '0071_auto_20210913_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='bulk_upload_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='ooi_ci_tools.bulkuploadevent'),
        ),
    ]
