# Generated by Django 3.1.3 on 2022-02-23 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0024_cruiseevent_vesselevent'),
        ('inventory', '0074_auto_20211106_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='cruise_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='ooi_ci_tools.cruiseevent'),
        ),
        migrations.AddField(
            model_name='action',
            name='vessel_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='ooi_ci_tools.vesselevent'),
        ),
        migrations.AlterField(
            model_name='action',
            name='object_type',
            field=models.CharField(blank=True, choices=[('build', 'Build'), ('inventory', 'Inventory'), ('deployment', 'Deployment'), ('calibrationevent', 'Calibration Event'), ('constdefaultevent', 'Constant Default Event'), ('configevent', 'Configuration/Constant Event'), ('configdefaultevent', 'Configuration Default Event'), ('coefficientnameevent', 'Coefficient Name Event'), ('confignameevent', 'Configuration Name Event'), ('location', 'Location'), ('vessel', 'Vessel'), ('cruise', 'Cruise'), ('referencedesignatorevent', 'Reference Designator Event'), ('bulkuploadevent', 'Bulk Upload Event'), ('cruiseevent', 'Cruise Event'), ('vesselevent', 'Vessel Event')], db_index=True, max_length=25),
        ),
    ]
