# Generated by Django 2.2.4 on 2019-08-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0074_auto_20190802_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='ooi_property_number',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='whoi_number',
        ),
    ]
