# Generated by Django 3.1.3 on 2022-08-30 15:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0075_auto_20220223_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='inventory.inventory')),
                ('inventory_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='inventory.inventorytest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
