# Generated by Django 2.2.4 on 2019-10-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0075_auto_20190807_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='custom_field_values',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='mooring_part',
        ),
    ]
