# Generated by Django 3.1.3 on 2022-09-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0077_inventorytestresult_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytestresult',
            name='detail',
            field=models.TextField(blank=True),
        ),
    ]
