# Generated by Django 3.1.3 on 2022-09-01 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0078_inventorytestresult_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorytestresult',
            old_name='detail',
            new_name='notes',
        ),
    ]
