# Generated by Django 3.1.3 on 2022-09-06 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0079_auto_20220901_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytestresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
