# Generated by Django 2.2.9 on 2020-02-18 15:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0004_auto_20191029_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_code', models.CharField(db_index=True, default='A', max_length=255)),
                ('revision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='assemblies.Assembly')),
            ],
            options={
                'ordering': ['-created_at', '-revision_code'],
            },
        ),
    ]
