# Generated by Django 2.2.9 on 2020-02-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0005_assemblyrevision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblydocument',
            name='assembly',
        ),
        migrations.AddField(
            model_name='assemblydocument',
            name='assembly_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assembly_documents', to='assemblies.AssemblyRevision'),
        ),
        migrations.AlterField(
            model_name='assemblyrevision',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_revisions', to='assemblies.Assembly'),
        ),
    ]
