# Generated by Django 2.2.4 on 2019-08-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0005_assembly_assembly_type'),
    ]

    operations = [
        migrations.RunSQL("select setval('assemblies_assemblypart_id_seq', 4000);")
    ]
