# Generated by Django 2.2.9 on 2020-02-19 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0007_assemblypart_assembly_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblypart',
            name='assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assembly_parts', to='assemblies.Assembly'),
        ),
    ]
