# Generated by Django 2.2.10 on 2020-03-25 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0008_auto_20200219_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assemblyrevision',
            options={'get_latest_by': 'created_at', 'ordering': ['-id', '-revision_code']},
        ),
        migrations.AlterField(
            model_name='assemblyrevision',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Release Date'),
        ),
    ]
