# Generated by Django 3.1.3 on 2020-11-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0010_auto_20201014_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
