# Generated by Django 3.1.3 on 2021-06-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0011_auto_20201117_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblydocument',
            name='doc_link',
            field=models.URLField(max_length=1000),
        ),
    ]
