# Generated by Django 3.1.3 on 2021-06-03 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0009_auto_20210603_1622'),
        ('assemblies', '0011_auto_20201117_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblypart',
            name='reference_designator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assembly_parts', to='ooi_ci_tools.referencedesignator'),
        ),
    ]
