# Generated by Django 3.1.3 on 2021-06-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0013_auto_20210610_1842'),
        ('assemblies', '0012_auto_20210609_0619'),
    ]

    operations = [
    ]
