# Generated by Django 3.1.3 on 2022-11-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0015_auto_20210611_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblypart',
            name='ci_deployedBy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assemblypart',
            name='ci_deployment_depth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assemblypart',
            name='ci_electrical_uid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assemblypart',
            name='ci_mooring_uid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assemblypart',
            name='ci_node_uid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assemblypart',
            name='ci_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assemblypart',
            name='ci_orbit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assemblypart',
            name='ci_recoveredBy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assemblypart',
            name='ci_versionNumber',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
