# Generated by Django 2.2.4 on 2019-10-22 15:10

from django.db import migrations
import environ

env = environ.Env()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model
        User = get_user_model()

        #DJANGO_DB_NAME = os.environ.get('DJANGO_DB_NAME', "default")
        DJANGO_SU_NAME = env('DJANGO_SU_NAME')
        DJANGO_SU_EMAIL = env('DJANGO_SU_EMAIL')
        DJANGO_SU_PASSWORD = env('DJANGO_SU_PASSWORD')

        superuser = User.objects.create_superuser(
            username=DJANGO_SU_NAME,
            email=DJANGO_SU_EMAIL,
            password=DJANGO_SU_PASSWORD)

        superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]
