# Generated by Django 2.2.4 on 2019-10-22 15:10
import environ

from django.db import migrations
from django.apps import apps
from django.contrib.auth import get_user_model
from django.contrib.auth.management import create_permissions

User = get_user_model()
Group = apps.get_model('auth','Group')
env = environ.Env()

def generate_superuser(apps, schema_editor):

    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

    DJANGO_SU_NAME = env('DJANGO_SU_NAME')
    DJANGO_SU_EMAIL = env('DJANGO_SU_EMAIL')
    DJANGO_SU_PASSWORD = env('DJANGO_SU_PASSWORD')

    group = Group.objects.get(name='admin')

    superuser = User.objects.create_superuser(
        username=DJANGO_SU_NAME,
        email=DJANGO_SU_EMAIL,
        password=DJANGO_SU_PASSWORD)

    superuser.save()
    superuser.groups.add(group)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_superuser),
    ]
