# Generated by Django 2.2.13 on 2020-07-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191023_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_infield',
            field=models.BooleanField(default=False),
        ),
    ]
