# Generated by Django 2.0 on 2018-04-17 14:36

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0006_auto_20180122_1529'),
        ('parts', '0030_auto_20180416_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='MooringPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('location', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mooring_parts', to='locations.Location')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='moorings.MooringPart')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mooring_parts', to='parts.Part')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
