# Generated by Django 2.0 on 2018-04-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moorings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooringpart',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
