# Generated by Django 2.2.4 on 2019-10-14 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moorings', '0001_initial'),
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooringpart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mooring_parts', to='parts.Part'),
        ),
    ]
