# Generated by Django 2.0.6 on 2018-06-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moorings', '0002_mooringpart_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooringpart',
            name='order',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
