# Generated by Django 2.0.6 on 2018-07-24 14:17

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('moorings', '0003_mooringpart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mooringpart',
            name='location',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mooring_parts', to='locations.Location'),
        ),
    ]
