# Generated by Django 2.0.6 on 2018-07-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moorings', '0004_auto_20180724_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mooringpart',
            name='order',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
