# Generated by Django 2.0.6 on 2018-08-08 13:51

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('moorings', '0005_auto_20180725_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mooringpart',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='moorings.MooringPart'),
        ),
    ]
