# Generated by Django 3.1.3 on 2021-10-28 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configs_constants', '0028_merge_20210610_1729'),
        ('assemblies', '0015_auto_20210611_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Grey'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Orange'), ('info', 'Light Blue'), ('light', 'Light'), ('dark', 'Dark')], default='warning', max_length=255)),
                ('pill', models.BooleanField(default=False)),
                ('assembly_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='assemblies.assemblypart')),
                ('config_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='configs_constants.configname')),
            ],
        ),
    ]
