# Generated by Django 2.2.10 on 2020-06-09 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0007_auto_20200430_1846'),
        ('parts', '0007_auto_20200420_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField(choices=[(True, 'Approved'), (False, 'Draft')], default=False)),
                ('deployment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_events', to='inventory.Deployment')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_events', to='inventory.Inventory')),
                ('user_approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_events_approver', to=settings.AUTH_USER_MODEL)),
                ('user_draft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_events_drafter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-configuration_date'],
            },
        ),
        migrations.CreateModel(
            name='ConfigName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('config_type', models.CharField(choices=[('ct', 'Constant'), ('cf', 'Configuration')], default='ct', max_length=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_names', to='parts.Part')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('part', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ConfigValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_value', models.CharField(db_index=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('config_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_values', to='configs_constants.ConfigEvent')),
                ('config_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_values', to='configs_constants.ConfigName')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('config_event', 'config_name')},
            },
        ),
    ]
