# Generated by Django 2.2.10 on 2020-06-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs_constants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configname',
            name='config_type',
            field=models.CharField(choices=[('cnst', 'Constant'), ('conf', 'Configuration')], default='ct', max_length=4),
        ),
    ]
