# Generated by Django 2.2.13 on 2020-07-10 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configs_constants', '0003_auto_20200612_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_value', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('config_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constant_defaults', to='configs_constants.ConfigEvent')),
                ('config_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constant_defaults', to='configs_constants.ConfigName')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('config_event', 'config_name')},
            },
        ),
    ]
