# Generated by Django 2.2.13 on 2020-07-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs_constants', '0004_constdefault'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='constdefault',
            unique_together={('config_name', 'default_value')},
        ),
        migrations.RemoveField(
            model_name='constdefault',
            name='config_event',
        ),
    ]
