# Generated by Django 2.2.13 on 2020-07-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs_constants', '0006_auto_20200710_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configname',
            name='config_type',
            field=models.CharField(choices=[('cnst', 'Constant'), ('conf', 'Configuration')], default='cnst', max_length=4),
        ),
        migrations.AlterField(
            model_name='constdefault',
            name='default_value',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
