# Generated by Django 2.2.13 on 2020-07-10 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_auto_20200709_1404'),
        ('configs_constants', '0007_auto_20200710_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='constdefault',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constant_defaults', to='inventory.Inventory'),
        ),
        migrations.AlterField(
            model_name='configvalue',
            name='config_value',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
