# Generated by Django 2.2.13 on 2020-07-13 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_auto_20200709_1404'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configs_constants', '0008_auto_20200710_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constdefault',
            name='inventory',
        ),
        migrations.CreateModel(
            name='ConstDefaultEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(choices=[(True, 'Approved'), (False, 'Draft')], default=False)),
                ('detail', models.TextField(blank=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constant_default_events', to='inventory.Inventory')),
                ('user_approver', models.ManyToManyField(related_name='constant_default_events_approver', to=settings.AUTH_USER_MODEL)),
                ('user_draft', models.ManyToManyField(related_name='constant_default_events_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='constdefault',
            name='const_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constant_defaults', to='configs_constants.ConstDefaultEvent'),
        ),
    ]
