# Generated by Django 2.2.13 on 2020-07-16 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configs_constants', '0010_auto_20200713_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='configevent',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='configevent',
            name='user_approver',
        ),
        migrations.AddField(
            model_name='configevent',
            name='user_approver',
            field=models.ManyToManyField(related_name='config_events_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='configevent',
            name='user_draft',
        ),
        migrations.AddField(
            model_name='configevent',
            name='user_draft',
            field=models.ManyToManyField(related_name='config_events_reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
