# Generated by Django 2.2.13 on 2020-07-20 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_merge_20200617_1450'),
        ('configs_constants', '0011_auto_20200716_1806'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configname',
            unique_together={('part', 'config_type', 'name')},
        ),
    ]
