# Generated by Django 2.2.13 on 2020-07-22 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0009_auto_20200325_1432'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configs_constants', '0012_auto_20200720_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigDefaultEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(choices=[(True, 'Approved'), (False, 'Draft')], default=False)),
                ('detail', models.TextField(blank=True)),
                ('assembly_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_default_events', to='assemblies.AssemblyPart')),
                ('user_approver', models.ManyToManyField(related_name='config_default_events_approver', to=settings.AUTH_USER_MODEL)),
                ('user_draft', models.ManyToManyField(related_name='config_default_events_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_value', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conf_def_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_defaults', to='configs_constants.ConfigDefaultEvent')),
                ('config_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_defaults', to='configs_constants.ConfigName')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('conf_def_event', 'config_name')},
            },
        ),
    ]
