# Generated by Django 2.2.13 on 2020-08-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs_constants', '0013_configdefault_configdefaultevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='configname',
            name='include_with_calibrations',
            field=models.BooleanField(default=False),
        ),
    ]
