# Generated by Django 2.2.13 on 2020-09-01 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs_constants', '0015_auto_20200817_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configdefaultevent',
            name='user_draft',
            field=models.ManyToManyField(blank=True, related_name='config_default_events_reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configevent',
            name='user_draft',
            field=models.ManyToManyField(blank=True, related_name='config_events_reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='confignameevent',
            name='user_draft',
            field=models.ManyToManyField(blank=True, related_name='config_name_events_reviewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='constdefaultevent',
            name='user_draft',
            field=models.ManyToManyField(blank=True, related_name='constant_default_events_reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
