# Generated by Django 2.2.13 on 2020-09-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs_constants', '0017_configevent_config_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='configname',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
