# Generated by Django 3.1.3 on 2021-01-15 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs_constants', '0019_auto_20201217_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigEventHyperlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=1000)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperlinks', to='configs_constants.configevent')),
            ],
            options={
                'ordering': ['text'],
            },
        ),
    ]
