# Generated by Django 3.1.3 on 2021-04-26 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0011_auto_20201117_2030'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0017_merge_20210209_1909'),
        ('configs_constants', '0022_auto_20210426_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='configdefaultevent',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_configdefaultevents', to='parts.part'),
        ),
        migrations.AddField(
            model_name='confignameevent',
            name='assembly_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assemblypart_confignameevents', to='assemblies.assemblypart'),
        ),
        migrations.AlterField(
            model_name='configdefaultevent',
            name='assembly_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assemblypart_configdefaultevents', to='assemblies.assemblypart'),
        ),
        migrations.AlterField(
            model_name='configdefaultevent',
            name='user_approver',
            field=models.ManyToManyField(related_name='approver_configdefaultevents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configdefaultevent',
            name='user_draft',
            field=models.ManyToManyField(blank=True, related_name='reviewer_configdefaultevents', to=settings.AUTH_USER_MODEL),
        ),
    ]
