# Generated by Django 3.1.3 on 2021-05-12 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0068_auto_20210512_1446'),
        ('configs_constants', '0023_auto_20210426_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='configdefaultevent',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_configdefaultevents', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='confignameevent',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_confignameevents', to='inventory.inventory'),
        ),
    ]
