# Generated by Django 3.1.3 on 2021-05-14 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0068_auto_20210512_1446'),
        ('assemblies', '0011_auto_20201117_2030'),
        ('parts', '0017_merge_20210209_1909'),
        ('configs_constants', '0025_auto_20210512_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='configevent',
            name='assembly_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assemblypart_configevents', to='assemblies.assemblypart'),
        ),
        migrations.AddField(
            model_name='configevent',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_configevents', to='parts.part'),
        ),
        migrations.AlterField(
            model_name='configevent',
            name='deployment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment_configevents', to='inventory.deployment'),
        ),
        migrations.AlterField(
            model_name='configevent',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_configevents', to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='configevent',
            name='user_approver',
            field=models.ManyToManyField(related_name='approver_configevents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configevent',
            name='user_draft',
            field=models.ManyToManyField(blank=True, related_name='reviewer_configevents', to=settings.AUTH_USER_MODEL),
        ),
    ]
