# Generated by Django 3.1.3 on 2021-06-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs_constants', '0027_auto_20210514_1635'),
        ('configs_constants', '0024_auto_20210609_0619'),
    ]

    operations = [
    ]
