# Generated by Django 2.2.9 on 2020-02-25 16:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('coefficient', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
    ]
