# Generated by Django 2.2.9 on 2020-05-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_auto_20200420_1935'),
        ('calibrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coefficientname',
            unique_together={('part', 'calibration_name')},
        ),
    ]
