# Generated by Django 2.2.9 on 2020-04-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coefficientvalue',
            name='notation_format',
            field=models.NullBooleanField(choices=[(True, 'Scientific'), (False, 'Engineering'), (None, 'Standard')], default=None),
        ),
    ]
