# Generated by Django 2.2.9 on 2020-03-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coefficient',
            name='name',
        ),
    ]
