# Generated by Django 2.2.9 on 2020-03-09 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0002_remove_coefficient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coefficient',
            name='calibration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coefficient', to='calibrations.Calibration'),
        ),
    ]
