# Generated by Django 2.2.9 on 2020-04-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0002_coefficientvalue_notation_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficientvalue',
            name='notation_format',
            field=models.NullBooleanField(choices=[(True, 'scientific'), (False, 'engineering'), (None, 'standard')], default=None),
        ),
    ]
