# Generated by Django 2.2.9 on 2020-03-13 23:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20191023_1735'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_auto_20191023_1347'),
        ('calibrations', '0003_coefficient_calibration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('calibration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField(choices=[(True, 'Approved'), (False, 'Draft')], default=False)),
                ('deployment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calibration_events', to='inventory.Deployment')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_events', to='inventory.Inventory')),
                ('user_approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_events_approver', to=settings.AUTH_USER_MODEL)),
                ('user_draft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_events_drafter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoefficientName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_name', models.CharField(db_index=True, max_length=255)),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coefficient_names', to='parts.Part')),
            ],
        ),
        migrations.CreateModel(
            name='CoefficientValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('calibration_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coefficient_values', to='calibrations.CalibrationEvent')),
                ('coefficient_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coefficient_values', to='calibrations.CoefficientName')),
            ],
        ),
        migrations.RemoveField(
            model_name='coefficient',
            name='calibration',
        ),
        migrations.RemoveField(
            model_name='coefficient',
            name='inventory',
        ),
        migrations.DeleteModel(
            name='Calibration',
        ),
        migrations.DeleteModel(
            name='Coefficient',
        ),
    ]
