# Generated by Django 2.2.9 on 2020-05-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0003_auto_20200522_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficientvalueset',
            name='value_set',
            field=models.TextField(blank=True, help_text='Enter value(s) in either Standard or Scientific Notation (#.##e10, #.##E-12)'),
        ),
    ]
