# Generated by Django 2.2.9 on 2020-04-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0003_auto_20200409_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficientvalue',
            name='notation_format',
            field=models.CharField(choices=[('scientific', 'Scientific'), ('engineering', 'Engineering'), ('standard', 'Standard')], default='standard', max_length=12),
        ),
    ]
