# Generated by Django 2.2.10 on 2020-05-29 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0004_auto_20200522_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficientvalue',
            name='notation_format',
            field=models.CharField(choices=[('sci', 'Scientific'), ('std', 'Standard')], default='std', max_length=3),
        ),
        migrations.AlterField(
            model_name='coefficientvalue',
            name='sigfig',
            field=models.IntegerField(blank=True, default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
