# Generated by Django 2.2.9 on 2020-03-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0005_auto_20200317_1916'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coefficientname',
            name='unique_name',
        ),
        migrations.AlterField(
            model_name='coefficientvalue',
            name='value',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='coefficientname',
            constraint=models.UniqueConstraint(fields=('part', 'calibration_name'), name='unique_name'),
        ),
    ]
