# Generated by Django 2.2.10 on 2020-05-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0005_auto_20200529_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='coefficientvalue',
            name='original_value',
            field=models.CharField(max_length=21, null=True),
        ),
    ]
