# Generated by Django 2.2.9 on 2020-03-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0006_auto_20200323_1851'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coefficientname',
            name='unique_name',
        ),
        migrations.AddConstraint(
            model_name='coefficientname',
            constraint=models.UniqueConstraint(fields=('calibration_name', 'part'), name='unique_name'),
        ),
    ]
