# Generated by Django 2.2.10 on 2020-06-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0006_coefficientvalue_original_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calibrationevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
