# Generated by Django 2.2.9 on 2020-03-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0007_auto_20200323_1900'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coefficientname',
            name='unique_name',
        ),
        migrations.AddConstraint(
            model_name='coefficientname',
            constraint=models.UniqueConstraint(fields=('part',), name='unique_names_per_part'),
        ),
    ]
