# Generated by Django 2.2.9 on 2020-03-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0008_auto_20200323_1940'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coefficientname',
            name='unique_names_per_part',
        ),
        migrations.AddConstraint(
            model_name='coefficientname',
            constraint=models.UniqueConstraint(fields=('part', 'calibration_name'), name='unique_names_per_part'),
        ),
    ]
