# Generated by Django 2.2.10 on 2020-06-10 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0009_auto_20200608_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficientname',
            name='sigfig_override',
            field=models.IntegerField(blank=True, default=3, help_text='Part-based default if sigfigs cannot be captured from input', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
