# Generated by Django 2.2.9 on 2020-03-30 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0009_auto_20200323_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficientvalue',
            name='value',
            field=models.CharField(max_length=20, validators=[django.core.validators.DecimalValidator(12, 12), django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
