# Generated by Django 2.2.13 on 2020-06-19 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calibrations', '0010_auto_20200610_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationevent',
            name='user_draft',
        ),
        migrations.AddField(
            model_name='calibrationevent',
            name='user_draft',
            field=models.ManyToManyField(related_name='calibration_events_drafter', to=settings.AUTH_USER_MODEL),
        ),
    ]
