# Generated by Django 2.2.13 on 2020-06-22 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0011_auto_20200619_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationevent',
            name='user_draft',
            field=models.ManyToManyField(blank=True, related_name='calibration_events_drafter', to=settings.AUTH_USER_MODEL),
        ),
    ]
