# Generated by Django 2.2.9 on 2020-04-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0011_auto_20200401_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficientvalue',
            name='value',
            field=models.CharField(max_length=20),
        ),
    ]
