# Generated by Django 2.2.13 on 2020-06-23 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0012_auto_20200622_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationevent',
            name='user_draft',
            field=models.ManyToManyField(related_name='calibration_events_drafter', to=settings.AUTH_USER_MODEL),
        ),
    ]
