# Generated by Django 2.2.9 on 2020-04-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0013_auto_20200401_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficientname',
            name='calibration_name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
