# Generated by Django 2.2.9 on 2020-04-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0014_auto_20200403_1650'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coefficientname',
            name='unique_names_per_part',
        ),
        migrations.AddConstraint(
            model_name='coefficientname',
            constraint=models.UniqueConstraint(fields=('calibration_name', 'part'), name='unique_names_per_part'),
        ),
    ]
