# Generated by Django 2.2.9 on 2020-04-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0015_auto_20200403_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficientname',
            name='calibration_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
