# Generated by Django 2.2.13 on 2020-07-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0015_calibrationevent_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficientname',
            name='value_set_type',
            field=models.CharField(choices=[('sl', 'Single'), ('1d', '1-Dimensional Array'), ('2d', '2-Dimensional Array')], default='sl', max_length=3),
        ),
    ]
