# Generated by Django 2.2.13 on 2020-08-12 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0008_merge_20200617_1450'),
        ('calibrations', '0017_auto_20200724_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoefficientNameEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(choices=[(True, 'Approved'), (False, 'Draft')], default=False)),
                ('detail', models.TextField(blank=True)),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coefficient_name_events', to='parts.Part')),
                ('user_approver', models.ManyToManyField(related_name='coefficient_name_events_approvers', to=settings.AUTH_USER_MODEL)),
                ('user_draft', models.ManyToManyField(related_name='coefficient_name_events_reviewers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='coefficientname',
            name='coeff_name_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coefficient_names', to='calibrations.CoefficientNameEvent'),
        ),
    ]
