# Generated by Django 2.2.13 on 2020-09-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0021_coefficientname_deprecated'),
        ('calibrations', '0021_auto_20200916_1607'),
    ]

    operations = [
    ]
