# Generated by Django 3.1.3 on 2021-01-15 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0022_merge_20200923_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationEventHyperlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=1000)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperlinks', to='calibrations.calibrationevent')),
            ],
            options={
                'ordering': ['text'],
            },
        ),
    ]
