# Generated by Django 3.1.3 on 2021-03-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0023_calibrationeventhyperlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficientname',
            name='sigfig_override',
            field=models.IntegerField(blank=True, default=3, help_text='Part-based default if sigfigs cannot be captured from input'),
        ),
    ]
