# Generated by Django 3.1.3 on 2021-03-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0024_auto_20210310_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='coefficientname',
            name='threshold_high',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='coefficientname',
            name='threshold_low',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
