# Generated by Django 3.1.3 on 2021-03-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0025_auto_20210331_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficientname',
            name='threshold_high',
            field=models.CharField(blank=True, help_text='Coefficient Threshold High override. (Digits + 1 optional decimal point)', max_length=255),
        ),
        migrations.AlterField(
            model_name='coefficientname',
            name='threshold_low',
            field=models.CharField(blank=True, help_text='Coefficient Threshold Low override. (Digits + 1 optional decimal point)', max_length=255),
        ),
    ]
