# Generated by Django 3.1.3 on 2021-04-21 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0017_merge_20210209_1909'),
        ('calibrations', '0026_auto_20210331_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficientnameevent',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_coefficientnameevents', to='parts.part'),
        ),
        migrations.AlterField(
            model_name='coefficientnameevent',
            name='user_approver',
            field=models.ManyToManyField(related_name='coefficientnameevent_approvers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coefficientnameevent',
            name='user_draft',
            field=models.ManyToManyField(blank=True, related_name='coefficientnameevent_reviewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
