# Generated by Django 3.1.3 on 2021-04-26 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calibrations', '0027_auto_20210421_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficientnameevent',
            name='user_approver',
            field=models.ManyToManyField(related_name='approver_coefficientnameevents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coefficientnameevent',
            name='user_draft',
            field=models.ManyToManyField(blank=True, related_name='reviewer_coefficientnameevents', to=settings.AUTH_USER_MODEL),
        ),
    ]
