# Generated by Django 3.1.3 on 2021-05-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0068_auto_20210512_1446'),
        ('calibrations', '0030_coefficientnameevent_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='coefficientnameevent',
            name='deployment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment_coefficientnameevents', to='inventory.deployment'),
        ),
    ]
