# Generated by Django 3.1.3 on 2021-06-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0030_auto_20210609_0619'),
        ('calibrations', '0032_auto_20210512_1452'),
    ]

    operations = [
    ]
