# Generated by Django 3.1.3 on 2021-03-19 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs_constants', '0020_configeventhyperlink'),
        ('calibrations', '0024_auto_20210310_1852'),
        ('ooi_ci_tools', '0003_importconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('low', models.CharField(max_length=255)),
                ('high', models.CharField(max_length=255)),
                ('coefficient_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='calibrations.coefficientname')),
                ('config_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='configs_constants.configname')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
