# Generated by Django 3.1.3 on 2021-03-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0004_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='importconfig',
            name='require_calibration_coefficient_threshold',
            field=models.BooleanField(default=False),
        ),
    ]
