# Generated by Django 3.1.3 on 2021-05-20 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0068_auto_20210512_1446'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0017_merge_20210209_1909'),
        ('assemblies', '0011_auto_20201117_2030'),
        ('ooi_ci_tools', '0005_importconfig_require_calibration_coefficient_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDesignator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(choices=[(True, 'Approved'), (False, 'Draft')], default=False)),
                ('detail', models.TextField(blank=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('assembly_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assemblypart_referencedesignators', to='assemblies.assemblypart')),
                ('deployment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment_referencedesignators', to='inventory.deployment')),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_referencedesignators', to='inventory.inventory')),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_referencedesignators', to='parts.part')),
                ('user_approver', models.ManyToManyField(related_name='approver_referencedesignators', to=settings.AUTH_USER_MODEL)),
                ('user_draft', models.ManyToManyField(blank=True, related_name='reviewer_referencedesignators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
