# Generated by Django 3.1.3 on 2021-05-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0006_referencedesignator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencedesignator',
            options={'ordering': ['name']},
        ),
    ]
