# Generated by Django 3.1.3 on 2021-05-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0007_auto_20210527_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencedesignator',
            options={'ordering': ['-created_at']},
        ),
    ]
