# Generated by Django 3.1.3 on 2021-06-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0009_auto_20210603_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencedesignator',
            options={'ordering': ['refdes_name']},
        ),
        migrations.RenameField(
            model_name='referencedesignator',
            old_name='name',
            new_name='refdes_name',
        ),
    ]
