# Generated by Django 3.1.3 on 2021-06-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0010_auto_20210615_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importconfig',
            old_name='require_vessel_prefix',
            new_name='require_vessel_vesseldesignation',
        ),
        migrations.RemoveField(
            model_name='importconfig',
            name='require_vessel_vessel_designation',
        ),
    ]
