# Generated by Django 3.1.3 on 2021-07-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0012_mpttcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedesignator',
            name='instrument',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='referencedesignator',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='referencedesignator',
            name='max_depth',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='referencedesignator',
            name='min_depth',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='referencedesignator',
            name='model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='referencedesignator',
            name='toc_l1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='referencedesignator',
            name='toc_l2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='referencedesignator',
            name='toc_l3',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
