# Generated by Django 3.1.3 on 2021-08-02 18:09

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0013_auto_20210722_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpttcomment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ooi_ci_tools.mpttcomment'),
        ),
    ]
