# Generated by Django 3.1.3 on 2021-08-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0014_auto_20210802_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencedesignator',
            name='max_depth',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='referencedesignator',
            name='min_depth',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
