# Generated by Django 3.1.3 on 2021-09-02 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0015_auto_20210802_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencedesignator',
            name='refdes_event',
        ),
        migrations.AddField(
            model_name='referencedesignatorevent',
            name='reference_designator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdes_events', to='ooi_ci_tools.referencedesignator'),
        ),
    ]
