# Generated by Django 3.1.3 on 2021-09-15 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0018_auto_20210913_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkassetrecord',
            name='bulk_upload_event',
        ),
        migrations.RemoveField(
            model_name='bulkvocabrecord',
            name='bulk_upload_event',
        ),
        migrations.CreateModel(
            name='BulkFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('bulk_upload_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_files', to='ooi_ci_tools.bulkuploadevent')),
            ],
        ),
        migrations.AddField(
            model_name='bulkassetrecord',
            name='bulk_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_records', to='ooi_ci_tools.bulkfile'),
        ),
        migrations.AddField(
            model_name='bulkvocabrecord',
            name='bulk_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab_records', to='ooi_ci_tools.bulkfile'),
        ),
    ]
