# Generated by Django 3.1.3 on 2021-09-28 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0019_auto_20210915_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkassetrecord',
            name='bulk_upload_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_records', to='ooi_ci_tools.bulkuploadevent'),
        ),
        migrations.AddField(
            model_name='bulkvocabrecord',
            name='bulk_upload_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab_records', to='ooi_ci_tools.bulkuploadevent'),
        ),
    ]
