# Generated by Django 3.1.3 on 2021-09-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0020_auto_20210928_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkuploadevent',
            options={},
        ),
        migrations.RemoveField(
            model_name='bulkuploadevent',
            name='assembly_part',
        ),
        migrations.RemoveField(
            model_name='bulkuploadevent',
            name='deployment',
        ),
        migrations.RemoveField(
            model_name='bulkuploadevent',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='bulkuploadevent',
            name='part',
        ),
    ]
