# Generated by Django 3.1.3 on 2021-09-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0022_auto_20210928_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencedesignatorevent',
            name='assembly_part',
        ),
    ]
