# Generated by Django 3.1.3 on 2021-10-07 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0022_auto_20210928_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkassetrecord',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='bulkfile',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='bulkvocabrecord',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='bulkassetrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bulkfile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bulkvocabrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
