# Generated by Django 3.1.3 on 2021-09-28 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0016_assemblypart_reference_designator_event'),
        ('ooi_ci_tools', '0023_remove_referencedesignatorevent_assembly_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedesignatorevent',
            name='assembly_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assemblypart_referencedesignatorevents', to='assemblies.assemblypart'),
        ),
    ]
