# Generated by Django 3.1.3 on 2022-02-23 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ooi_ci_tools', '0023_auto_20211007_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(choices=[(True, 'Approved'), (False, 'Draft')], default=False)),
                ('detail', models.TextField(blank=True)),
                ('user_approver', models.ManyToManyField(related_name='approver_vesselevents', to=settings.AUTH_USER_MODEL)),
                ('user_draft', models.ManyToManyField(blank=True, related_name='reviewer_vesselevents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CruiseEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(choices=[(True, 'Approved'), (False, 'Draft')], default=False)),
                ('detail', models.TextField(blank=True)),
                ('user_approver', models.ManyToManyField(related_name='approver_cruiseevents', to=settings.AUTH_USER_MODEL)),
                ('user_draft', models.ManyToManyField(blank=True, related_name='reviewer_cruiseevents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
