# Generated by Django 3.1.3 on 2022-03-07 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0023_auto_20220302_1812'),
        ('ooi_ci_tools', '0025_auto_20220302_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruiseevent',
            name='cruise',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cruise_events', to='cruises.cruise'),
        ),
        migrations.AlterField(
            model_name='vesselevent',
            name='vessel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vessel_events', to='cruises.vessel'),
        ),
    ]
