# Generated by Django 2.2.4 on 2019-10-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('ip_domain', models.CharField(max_length=255, unique=True)),
                ('printer_type', models.CharField(choices=[('Brady', 'Brady'), ('Zebra', 'Zebra')], default='Brady', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
