# Generated by Django 2.0.12 on 2019-03-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admintools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'ordering': ['name']},
        ),
    ]
