# Generated by Django 2.2.4 on 2019-12-10 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admintools', '0003_tempimport_tempimportitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempimportitem',
            name='tempimport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tempimportitems', to='admintools.TempImport'),
        ),
    ]
