# Generated by Django 2.2.8 on 2020-01-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintools', '0004_tempimportitem_tempimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempimport',
            name='column_headers',
            field=models.TextField(blank=True),
        ),
    ]
