# Generated by Django 2.2.8 on 2020-01-09 17:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admintools', '0005_tempimport_column_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempimport',
            name='column_headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
