# Generated by Django 2.2.9 on 2020-01-14 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0004_auto_20191029_1914'),
        ('admintools', '0006_auto_20200109_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempImportAssembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('assembly_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('assembly_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_assemblies', to='assemblies.AssemblyType')),
            ],
        ),
    ]
