# Generated by Django 2.2.9 on 2020-01-14 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20191023_1735'),
        ('admintools', '0007_tempimportassembly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempimportassembly',
            name='assembly_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tempimportassembly',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='TempImportAssemblyPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_id', models.IntegerField(blank=True, null=True)),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_assembly_parts', to='admintools.TempImportAssembly')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_assembly_parts', to='parts.Part')),
            ],
        ),
    ]
