"""
# Copyright (C) 2019-2020 Woods Hole Oceanographic Institution
#
# This file is part of the Roundabout Database project ("RDB" or 
# "ooicgsn-roundabout").
#
# ooicgsn-roundabout is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# ooicgsn-roundabout is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ooicgsn-roundabout in the COPYING.md file at the project root.
# If not, see <http://www.gnu.org/licenses/>.
"""

# Generated by Django 2.2.9 on 2020-01-14 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20191023_1735'),
        ('admintools', '0007_tempimportassembly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempimportassembly',
            name='assembly_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tempimportassembly',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='TempImportAssemblyPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_id', models.IntegerField(blank=True, null=True)),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_assembly_parts', to='admintools.TempImportAssembly')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_assembly_parts', to='parts.Part')),
            ],
        ),
    ]
