# Generated by Django 2.2.9 on 2020-01-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintools', '0009_tempimportassembly_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempimportassemblypart',
            name='order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
