# Generated by Django 3.0.10 on 2020-10-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintools', '0011_auto_20200114_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempimportassemblypart',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='tempimportassemblypart',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='tempimportassemblypart',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
