# Generated by Django 2.2.13 on 2020-07-31 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0012_auto_20200727_1746'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admintools', '0011_auto_20200114_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_this_instance', models.BooleanField(default=False)),
                ('cruise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_instances', to='cruises.Cruise')),
                ('users', models.ManyToManyField(related_name='field_instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
