# Generated by Django 3.1.3 on 2021-02-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintools', '0012_auto_20201014_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempimport',
            name='column_headers',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='tempimportitem',
            name='data',
            field=models.JSONField(),
        ),
    ]
