# Generated by Django 3.1.3 on 2022-06-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintools', '0013_auto_20210204_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempimport',
            name='update_existing_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
