# Generated by Django 2.0.12 on 2019-05-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0048_auto_20190514_1602'),
        ('userdefinedfields', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='field_all_part_types',
        ),
        migrations.RemoveField(
            model_name='field',
            name='field_value_is_global',
        ),
        migrations.AddField(
            model_name='field',
            name='part_types',
            field=models.ManyToManyField(blank=True, to='parts.PartType'),
        ),
    ]
