# Generated by Django 2.2.10 on 2020-03-25 14:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedfields', '0002_auto_20191023_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='choice_field_options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('CharField', 'Text Field'), ('IntegerField', 'Integer Field'), ('DecimalField', 'Decimal Field'), ('BooleanField', 'Boolean Field'), ('DateField', 'Date Field'), ('ChoiceField', 'Dropdown Field')], max_length=100),
        ),
    ]
