# Generated by Django 2.0.12 on 2019-05-14 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_inventory_custom_field_values'),
        ('userdefinedfields', '0003_auto_20190514_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_value', models.CharField(blank=True, db_index=True, max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldvalues', to='userdefinedfields.Field')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldvalues', to='inventory.Inventory')),
            ],
            options={
                'ordering': ('field',),
            },
        ),
    ]
