# Generated by Django 2.2.10 on 2020-04-21 00:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedfields', '0003_auto_20200325_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='choice_field_options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
