# Generated by Django 2.2.10 on 2020-05-17 18:14

from django.apps import apps
from django.db import migrations

FieldValue = apps.get_model('userdefinedfields', 'FieldValue')

def remove_nulls(apps, schema_editor):
    for fv in FieldValue.objects.all():
        if fv.field_value is None:
            fv.field_value = ''
            fv.save()

class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedfields', '0004_auto_20200421_0056'),
    ]

    operations = [
        migrations.RunPython(remove_nulls),
    ]
