# Generated by Django 2.2.13 on 2020-07-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('userdefinedfields', '0005_auto_20200517_1814'), ('userdefinedfields', '0006_auto_20200517_1822')]

    dependencies = [
        ('userdefinedfields', '0004_auto_20200421_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvalue',
            name='field_value',
            field=models.TextField(blank=True),
        ),
    ]
