# Generated by Django 2.0.12 on 2019-05-15 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedfields', '0004_fieldvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
