# Generated by Django 2.2.13 on 2020-08-20 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedfields', '0005_auto_20200517_1814_squashed_0006_auto_20200517_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='field',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
