# Generated by Django 2.2.10 on 2020-05-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedfields', '0005_auto_20200517_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvalue',
            name='field_value',
            field=models.TextField(blank=True),
        ),
    ]
