# Generated by Django 2.0.12 on 2019-05-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedfields', '0005_fieldvalue_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
