# Generated by Django 2.0.12 on 2019-05-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedfields', '0006_fieldvalue_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldvalue',
            options={'get_latest_by': 'created_at', 'ordering': ('field', 'created_at')},
        ),
        migrations.RemoveField(
            model_name='fieldvalue',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
