# Generated by Django 2.0.12 on 2019-05-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedfields', '0008_field_value_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='value_is_locked',
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('CharField', 'Text Field'), ('IntegerField', 'Integer Field'), ('DecimalField', 'Decimal Field'), ('BooleanField', 'Boolean Field')], max_length=100),
        ),
    ]
