# Generated by Django 2.0.12 on 2019-05-20 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0048_auto_20190514_1602'),
        ('userdefinedfields', '0009_auto_20190520_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvalue',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldvalues', to='parts.Part'),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldvalues', to='inventory.Inventory'),
        ),
    ]
