# Generated by Django 2.0.12 on 2019-05-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedfields', '0010_auto_20190520_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='global_for_part_types',
            field=models.ManyToManyField(blank=True, related_name='custom_fields', to='parts.PartType'),
        ),
    ]
