# Generated by Django 2.0.12 on 2019-05-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedfields', '0011_auto_20190520_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvalue',
            name='is_default_value',
            field=models.BooleanField(default=False),
        ),
    ]
