# Generated by Django 2.0.12 on 2019-05-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedfields', '0012_fieldvalue_is_default_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('CharField', 'Text Field'), ('IntegerField', 'Integer Field'), ('DecimalField', 'Decimal Field'), ('BooleanField', 'Boolean Field'), ('DateField', 'Date Field')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='field_value',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
