# Generated by Django 2.2.1 on 2019-06-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedfields', '0014_fieldvalue_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvalue',
            name='field_value',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
