# Generated by Django 2.2.1 on 2019-06-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedfields', '0015_auto_20190619_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvalue',
            name='field_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
