# Generated by Django 2.2.10 on 2020-04-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0002_auto_20200421_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='IMO_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='MMSI_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='R2R',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='max_draft',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='max_speed',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
