# Generated by Django 2.2.10 on 2020-04-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0003_auto_20200421_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUID', models.CharField(max_length=20)),
                ('cruise_start_date', models.DateTimeField()),
                ('cruise_stop_date', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('vessel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cruises', to='cruises.Vessel')),
            ],
            options={
                'ordering': ('cruise_start_date',),
            },
        ),
    ]
