# Generated by Django 2.2.10 on 2020-04-22 14:44

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20191023_1513'),
        ('cruises', '0004_cruise'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='location',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cruises', to='locations.Location'),
        ),
    ]
