# Generated by Django 2.2.10 on 2020-04-24 20:51

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0005_cruise_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cruise',
            options={'ordering': ('-cruise_start_date',)},
        ),
        migrations.AlterField(
            model_name='cruise',
            name='location',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cruises', to='locations.Location', verbose_name='Destination'),
        ),
    ]
