# Generated by Django 2.2.10 on 2020-04-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0006_auto_20200424_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cruise',
            old_name='note',
            new_name='notes',
        ),
    ]
