# Generated by Django 2.2.13 on 2020-07-24 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0008_auto_20200513_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='IMO_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='MMSI_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(100000000)]),
        ),
        migrations.AddConstraint(
            model_name='vessel',
            constraint=models.CheckConstraint(check=models.Q(max_speed__gt='0'), name='max_speed_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='vessel',
            constraint=models.CheckConstraint(check=models.Q(max_draft__gt='0'), name='max_draft_gt_0'),
        ),
    ]
