# Generated by Django 2.2.13 on 2020-07-24 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0010_auto_20200724_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='ICES_code',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='IMO_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(9999999)]),
        ),
    ]
