# Generated by Django 2.2.13 on 2020-10-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0013_auto_20201001_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='vessel_designation',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
