# Generated by Django 3.1.3 on 2020-12-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0015_auto_20201117_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='CUID',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
