# Generated by Django 3.1.3 on 2021-01-05 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0015_auto_20201117_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('website', 'Website'), ('document', 'Document')], max_length=20)),
                ('doc_link', models.CharField(max_length=1000)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cruises.vessel')),
            ],
            options={
                'ordering': ['doc_type', 'name'],
            },
        ),
    ]
