# Generated by Django 3.1.3 on 2021-02-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0016_auto_20201211_1431'),
        ('cruises', '0018_cruisehyperlink'),
    ]

    operations = [
    ]
