# Generated by Django 3.1.3 on 2021-06-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0019_merge_20210209_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruisehyperlink',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
