# Generated by Django 3.1.3 on 2021-07-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0020_auto_20210609_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesselhyperlink',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
