# Generated by Django 3.1.3 on 2022-02-23 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ooi_ci_tools', '0024_cruiseevent_vesselevent'),
        ('cruises', '0021_auto_20210726_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='cruise_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cruises', to='ooi_ci_tools.cruiseevent'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='vessel_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vessels', to='ooi_ci_tools.vesselevent'),
        ),
    ]
