# Generated by Django 3.1.3 on 2022-03-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0022_auto_20220223_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='cruise_event',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='vessel_event',
        ),
    ]
